import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAuth } from "@/hooks/useAuth";
import { useActivityTracker } from "@/hooks/useActivityTracker";
import { Download, User, LogOut, FileText, Heart, CheckCircle } from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { useQuery } from "@tanstack/react-query";
import type { User as UserType, CampaignBrief } from "@shared/schema";

export default function Dashboard() {
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [showThankYouModal, setShowThankYouModal] = useState(false);
  const { user, logout, isLoggingOut, isAuthenticated } = useAuth();
  
  // Type guard for user
  const typedUser = user as UserType | undefined;

  // Fetch user's campaign briefs
  const { data: campaignBriefs = [], isLoading: isBriefsLoading } = useQuery<CampaignBrief[]>({
    queryKey: ["/api/campaign-briefs"],
    enabled: isAuthenticated,
  });

  // Get the most recent campaign brief
  const latestBrief = campaignBriefs.length > 0 ? campaignBriefs[campaignBriefs.length - 1] : null;

  // Auto-logout after 5 minutes of inactivity
  useActivityTracker({
    onInactivityTimeout: () => {
      console.log('User inactive for 5 minutes - auto logout');
      handleLogout();
    },
    timeoutMinutes: 5,
    isActive: isAuthenticated
  });

  const handleLogout = async () => {
    try {
      await logout();
      setShowThankYouModal(true);
    } catch (error) {
      console.error('Logout error:', error);
    }
  };

  const handleThankYouClose = () => {
    setShowThankYouModal(false);
    // Redirect to homepage after modal closes
    window.location.href = '/';
  };

  const generateCampaignBrief = async () => {
    if (!latestBrief) {
      console.error('No campaign brief available');
      return;
    }

    setIsGeneratingPDF(true);
    try {
      // Create the actual brief content using the campaign data
      const briefContent = document.createElement('div');
      briefContent.style.padding = '40px';
      briefContent.style.fontFamily = 'Arial, sans-serif';
      briefContent.style.backgroundColor = 'white';
      briefContent.style.width = '800px';
      
      // Parse AI insights if they exist
      const insights = latestBrief.aiInsights as any || {};
      const recommendations = insights.recommendations || [];
      const budgetAllocation = insights.budgetAllocation || {};
      const platformStrategies = insights.platformStrategies || {};
      const kpis = insights.kpis || [];
      
      briefContent.innerHTML = `
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="color: #1e40af; font-size: 28px; margin-bottom: 10px;">Digital Media Campaign Brief</h1>
          <h2 style="color: #1e40af; font-size: 22px; margin-bottom: 15px;">${latestBrief.clientName || latestBrief.campaignName}</h2>
          <p style="color: #6b7280; font-size: 16px;">Generated by YourBrief AI Media Strategist</p>
          <p style="color: #6b7280; font-size: 14px;">${new Date(latestBrief.createdAt || new Date()).toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}</p>
        </div>
        
        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Campaign Overview</h2>
          <p style="color: #6b7280; line-height: 1.6;">
            <strong>Client:</strong> ${latestBrief.clientName}<br>
            <strong>Campaign:</strong> ${latestBrief.campaignName}<br>
            <strong>Target Audience:</strong> ${latestBrief.targetAudience}<br>
            <strong>Budget:</strong> ${latestBrief.budget}<br>
            <strong>Platforms:</strong> ${latestBrief.platforms}<br>
            <strong>Timeline:</strong> ${latestBrief.timeline}
          </p>
        </div>

        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Campaign Objectives</h2>
          <p style="color: #6b7280; line-height: 1.6;">
            ${latestBrief.objectives}
          </p>
        </div>

        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Key Messages</h2>
          <p style="color: #6b7280; line-height: 1.6;">
            ${latestBrief.keyMessages}
          </p>
        </div>

        ${recommendations.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Strategic Recommendations</h2>
          <ul style="color: #6b7280; line-height: 1.6; padding-left: 20px;">
            ${recommendations.map((rec: string) => `<li>${rec}</li>`).join('')}
          </ul>
        </div>
        ` : ''}

        ${Object.keys(budgetAllocation).length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Budget Allocation</h2>
          <div style="color: #6b7280; line-height: 1.6;">
            ${Object.entries(budgetAllocation).map(([platform, allocation]) => 
              `<p><strong>${platform}:</strong> ${allocation}</p>`
            ).join('')}
          </div>
        </div>
        ` : ''}

        ${Object.keys(platformStrategies).length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Platform-Specific Strategies</h2>
          <div style="color: #6b7280; line-height: 1.6;">
            ${Object.entries(platformStrategies).map(([platform, strategy]) => 
              `<div style="margin-bottom: 15px;"><strong>${platform}:</strong><br>${strategy}</div>`
            ).join('')}
          </div>
        </div>
        ` : ''}

        ${insights.estimatedReach || insights.estimatedCPM ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Performance Estimates</h2>
          <p style="color: #6b7280; line-height: 1.6;">
            ${insights.estimatedReach ? `<strong>Estimated Reach:</strong> ${insights.estimatedReach}<br>` : ''}
            ${insights.estimatedCPM ? `<strong>Estimated CPM:</strong> ${insights.estimatedCPM}<br>` : ''}
          </p>
        </div>
        ` : ''}

        ${kpis.length > 0 ? `
        <div style="margin-bottom: 30px;">
          <h2 style="color: #374151; font-size: 20px; margin-bottom: 15px;">Key Performance Indicators</h2>
          <ul style="color: #6b7280; line-height: 1.6; padding-left: 20px;">
            ${kpis.map((kpi: string) => `<li>${kpi}</li>`).join('')}
          </ul>
        </div>
        ` : ''}

        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center;">
          Generated by YourBrief AI Media Strategist | Contact: ${typedUser?.email}
        </div>
      `;

      document.body.appendChild(briefContent);

      const canvas = await html2canvas(briefContent, {
        scale: 2,
        logging: false,
        useCORS: true,
        allowTaint: true
      });

      document.body.removeChild(briefContent);

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const imgWidth = 210;
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      // Use company name from brief data in filename
      const companyName = latestBrief.clientName || 'Campaign';
      const fileName = `${companyName.replace(/[^a-z0-9]/gi, '_')}_Campaign_Brief.pdf`;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(fileName);
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-100 dark:border-gray-700">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <h1 className="text-xl font-bold text-gray-900 dark:text-white">
                YourBrief Dashboard
              </h1>
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300">
                <User className="h-4 w-4" />
                <span>{typedUser?.firstName} {typedUser?.lastName}</span>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={handleLogout}
                disabled={isLoggingOut}
                data-testid="button-logout"
              >
                <LogOut className="h-4 w-4 mr-2" />
                {isLoggingOut ? "Logging out..." : "Logout"}
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Welcome Section */}
        <div className="text-center mb-12">
          <div className="relative">
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-32 h-32 bg-gradient-to-r from-blue-500/20 to-purple-500/20 rounded-full blur-3xl"></div>
            </div>
            <div className="relative">
              <h1 className="text-4xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 dark:from-white dark:to-gray-300 bg-clip-text text-transparent mb-4">
                Welcome back, {typedUser?.firstName}!
              </h1>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
                Your AI-powered digital media campaign planner is ready to help you create comprehensive campaign strategies.
              </p>
            </div>
          </div>
        </div>

        {/* Action Cards */}
        <div className="grid md:grid-cols-2 gap-8 mb-12">
          {/* Download Brief Card */}
          <Card className="bg-white dark:bg-gray-800 shadow-lg hover:shadow-xl transition-shadow duration-200">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-blue-600 rounded-lg flex items-center justify-center">
                  <Download className="h-5 w-5 text-white" />
                </div>
                {latestBrief ? "Campaign Brief" : "Create Campaign"}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600 dark:text-gray-300 mb-6">
                {latestBrief ? 
                  "Download your AI-generated campaign brief with comprehensive strategies, budget allocations, and platform-specific recommendations." :
                  "Complete a campaign questionnaire to generate and download your personalized AI campaign brief."
                }
              </p>
              <Button 
                onClick={latestBrief ? generateCampaignBrief : () => window.location.href = '/'}
                disabled={isGeneratingPDF || isBriefsLoading}
                size="lg"
                className="w-full bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg hover:shadow-xl transition-all duration-200"
                data-testid="button-download-brief"
              >
                <Download className="h-5 w-5 mr-2" />
                {isGeneratingPDF ? "Generating Brief..." : 
                 isBriefsLoading ? "Loading..." :
                 latestBrief ? "Download Brief" : "Create Campaign Brief"}
              </Button>
            </CardContent>
          </Card>

          {/* Create New Campaign Card */}
          <Card className="bg-white dark:bg-gray-800 shadow-lg hover:shadow-xl transition-shadow duration-200">
            <CardHeader>
              <CardTitle className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-r from-purple-500 to-purple-600 rounded-lg flex items-center justify-center">
                  <FileText className="h-5 w-5 text-white" />
                </div>
                Create New Campaign
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600 dark:text-gray-300 mb-6">
                Start a new campaign planning session with our AI assistant. Answer strategic questions to get personalized recommendations.
              </p>
              <Button 
                onClick={() => window.location.href = '/campaign-planner'}
                size="lg"
                variant="outline"
                className="w-full border-purple-200 dark:border-purple-700 hover:bg-purple-50 dark:hover:bg-purple-900/20 transition-all duration-200"
                data-testid="button-new-campaign"
              >
                <FileText className="h-5 w-5 mr-2" />
                Start Campaign Planner
              </Button>
            </CardContent>
          </Card>
        </div>

        {/* User Info */}
        <Card className="bg-gradient-to-r from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-700 border border-gray-200 dark:border-gray-600">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <User className="h-5 w-5 text-gray-600 dark:text-gray-300" />
              Account Information
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Name:</span>
                <p className="text-gray-900 dark:text-white" data-testid="text-user-name">
                  {typedUser?.firstName} {typedUser?.lastName}
                </p>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Email:</span>
                <p className="text-gray-900 dark:text-white" data-testid="text-user-email">
                  {typedUser?.email}
                </p>
              </div>
              {typedUser?.company && (
                <div className="md:col-span-2">
                  <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Company:</span>
                  <p className="text-gray-900 dark:text-white" data-testid="text-user-company">
                    {typedUser.company}
                  </p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      </main>

      {/* Thank You Modal */}
      <Dialog open={showThankYouModal} onOpenChange={setShowThankYouModal}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-3 justify-center text-center">
              <div className="w-12 h-12 bg-gradient-to-r from-green-500 to-green-600 rounded-full flex items-center justify-center">
                <CheckCircle className="h-6 w-6 text-white" />
              </div>
              <span className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 dark:from-white dark:to-gray-300 bg-clip-text text-transparent">
                Thank You!
              </span>
            </DialogTitle>
          </DialogHeader>
          <div className="text-center py-6">
            <div className="mb-6">
              <Heart className="h-8 w-8 text-red-500 mx-auto mb-4" />
              <p className="text-lg text-gray-700 dark:text-gray-300 mb-2">
                Thank you for using YourBrief!
              </p>
              <p className="text-gray-600 dark:text-gray-400">
                We hope our AI-powered campaign planner helped you create amazing digital media strategies.
              </p>
            </div>
            <Button 
              onClick={handleThankYouClose}
              size="lg"
              className="w-full bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg hover:shadow-xl transition-all duration-200"
              data-testid="button-thank-you-close"
            >
              Continue to Homepage
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}