import PDFDocument from "pdfkit";
import { DecisionObject } from "./decision-engine";
import { NarrativeOutput, mapBucketBandToLevel } from "./narrative-generator";

const COLORS = {
  primary: "#059669",
  secondary: "#0d9488",
  dark: "#1f2937",
  gray: "#6b7280",
  lightGray: "#f3f4f6",
  white: "#ffffff",
  riskLow: "#22c55e",
  riskModerate: "#eab308",
  riskHigh: "#f97316",
  riskVeryHigh: "#ef4444"
};

function getRiskColor(band: string): string {
  switch (band.toLowerCase()) {
    case "low": return COLORS.riskLow;
    case "moderate": return COLORS.riskModerate;
    case "high": return COLORS.riskHigh;
    case "very high": return COLORS.riskVeryHigh;
    default: return COLORS.riskModerate;
  }
}

export async function renderDecisionMemoPDF(
  decision: DecisionObject,
  narrative: NarrativeOutput["decisionMemo"]
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(24).fillColor(COLORS.primary).text("Margin Risk Decision Memo", { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Contact Information");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text(`Name: ${decision.engagementContext.fullName}`);
    doc.text(`Email: ${decision.engagementContext.workEmail}`);
    doc.text(`Organization: ${decision.engagementContext.organisationName}`);
    doc.text(`Role: ${decision.engagementContext.roleTitle}`);
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Executive Summary");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.executiveSummary, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.fontSize(12).fillColor(COLORS.secondary).font("Helvetica-Bold").text("Key Insight");
    doc.moveDown(0.3);
    doc.font("Helvetica-Oblique").fontSize(11).fillColor(COLORS.dark).text(narrative.keyInsight, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Risk Assessment");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11);
    doc.fillColor(COLORS.gray).text("• Structural Risk: ", { continued: true });
    doc.fillColor(getRiskColor(narrative.riskAssessment.structural)).text(narrative.riskAssessment.structural);
    doc.fillColor(COLORS.gray).text("• Behavioral Risk: ", { continued: true });
    doc.fillColor(getRiskColor(narrative.riskAssessment.behavioral)).text(narrative.riskAssessment.behavioral);
    doc.fillColor(COLORS.gray).text("• Overall Margin Risk: ", { continued: true });
    doc.fillColor(getRiskColor(narrative.riskAssessment.overall)).text(narrative.riskAssessment.overall);
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text("Margin erosion is likely to occur gradually through:");
    doc.fontSize(10).text("• Increased senior involvement");
    doc.text("• Untracked coordination effort");
    doc.text("• Informal scope absorption");
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Decision Guidance");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text("Proceed with the engagement, subject to the following controls:");
    doc.moveDown(0.3);
    narrative.decisionGuidance.forEach((guidance, index) => {
      doc.text(`${index + 1}. ${guidance}`, { lineGap: 3 });
    });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Recommendation");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.recommendation, { lineGap: 4 });

    doc.moveDown(2);
    doc.fontSize(8).fillColor(COLORS.gray).text(
      `Generated by MarginMix | Decision ID: ${decision.id} | ${new Date().toLocaleDateString()}`,
      { align: "center" }
    );

    doc.end();
  });
}

export async function renderAssessmentOutputPDF(
  decision: DecisionObject,
  narrative: NarrativeOutput["assessmentOutput"],
  openSignal: string | null
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(24).fillColor(COLORS.primary).text("Margin Risk Assessment Output", { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Contact Information");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text(`Name: ${decision.engagementContext.fullName}`);
    doc.text(`Email: ${decision.engagementContext.workEmail}`);
    doc.text(`Organization: ${decision.engagementContext.organisationName}`);
    doc.text(`Role: ${decision.engagementContext.roleTitle}`);
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Engagement Context");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text(`• Org size: ${decision.engagementContext.organisationSize}`);
    doc.text(`• Engagement type: ${decision.engagementContext.type}`);
    doc.text(`• Classification: ${decision.engagementContext.classification}`);
    doc.moveDown(1.5);

    if (openSignal) {
      doc.fontSize(12).fillColor(COLORS.secondary).font("Helvetica-Bold").text("Critical Open Signal");
      doc.moveDown(0.3);
      doc.font("Helvetica-Oblique").fontSize(11).fillColor(COLORS.dark).text(`"${openSignal}"`, { lineGap: 4 });
      doc.moveDown(0.5);
      doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text(narrative.criticalSignalAnalysis, { lineGap: 3 });
      doc.moveDown(1.5);
    }

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Risk Drivers");
    doc.moveDown(0.5);
    
    const drivers = [
      { name: "Structural Load", ...narrative.riskDrivers.structural },
      { name: "Behavioral Load", ...narrative.riskDrivers.behavioral },
      { name: "Governance Fragility", ...narrative.riskDrivers.governance }
    ];
    
    drivers.forEach((driver, index) => {
      doc.fontSize(12).fillColor(COLORS.dark).font("Helvetica-Bold").text(`${index + 1}. ${driver.name} — ${driver.level}`);
      doc.moveDown(0.3);
      doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text(driver.description, { lineGap: 3 });
      doc.moveDown(1);
    });

    const riskColor = getRiskColor(decision.riskBand);
    doc.rect(50, doc.y, 495, 50).fillAndStroke(riskColor, riskColor);
    doc.fontSize(16).fillColor(COLORS.white).font("Helvetica-Bold").text(
      `${decision.riskBand.toUpperCase()} MARGIN RISK`,
      60,
      doc.y - 45,
      { align: "center", width: 475 }
    );
    doc.fontSize(10).fillColor(COLORS.white).font("Helvetica").text(
      decision.marginRiskVerdict,
      60,
      doc.y - 25,
      { align: "center", width: 475 }
    );
    doc.y += 20;
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Effort Band Recommendations");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text("These bands are control limits, not guidelines.");
    doc.moveDown(0.5);

    doc.fontSize(12).fillColor(COLORS.dark).font("Helvetica-Bold").text("Senior Leadership");
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text(`• Target band: ${decision.effortPercentages.senior}`);
    doc.text(`• Rationale: ${narrative.effortBandRationale.senior}`);
    doc.moveDown(0.8);

    doc.fontSize(12).fillColor(COLORS.dark).font("Helvetica-Bold").text("Mid-Level (Account / Program Owners)");
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text(`• Target band: ${decision.effortPercentages.mid}`);
    doc.text(`• Rationale: ${narrative.effortBandRationale.midLevel}`);
    doc.moveDown(0.8);

    doc.fontSize(12).fillColor(COLORS.dark).font("Helvetica-Bold").text("Junior / Execution Layer");
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    doc.text(`• Target band: ${decision.effortPercentages.junior}`);
    doc.text(`• Rationale: ${narrative.effortBandRationale.junior}`);
    doc.moveDown(1.5);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Early Warning Indicators");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text("Trigger review if any one of the following occurs:");
    doc.moveDown(0.3);
    narrative.earlyWarningIndicators.forEach((indicator) => {
      doc.text(`• ${indicator}`, { lineGap: 3 });
    });

    doc.moveDown(2);
    doc.fontSize(8).fillColor(COLORS.gray).text(
      `Generated by MarginMix | Decision ID: ${decision.id} | ${new Date().toLocaleDateString()}`,
      { align: "center" }
    );

    doc.end();
  });
}

export function generatePDFFilename(
  type: "decision_memo" | "assessment_output",
  fullName: string,
  organisationName: string
): string {
  const sanitize = (str: string) => str.replace(/[^a-zA-Z0-9]/g, "_").substring(0, 30);
  const name = sanitize(fullName);
  const org = sanitize(organisationName);
  const timestamp = Date.now();
  
  if (type === "decision_memo") {
    return `MMIX_Margin_Risk_Decision_Memo_${name}_${org}_${timestamp}.pdf`;
  }
  return `MMIX_Margin_Risk_Assessment_Output_${name}_${org}_${timestamp}.pdf`;
}
