import PDFDocument from "pdfkit";
import { DecisionObject } from "./decision-engine";
import { NarrativeOutput } from "./narrative-generator";
import path from "path";
import fs from "fs";

const COLORS = {
  primary: "#059669",
  secondary: "#0d9488",
  dark: "#1f2937",
  gray: "#6b7280",
  lightGray: "#f3f4f6",
  white: "#ffffff",
  riskLow: "#22c55e",
  riskModerate: "#eab308",
  riskHigh: "#f97316",
  riskVeryHigh: "#ef4444"
};

const LOGO_PATH = path.join(process.cwd(), "server", "assets", "marginmix-logo.png");

function getRiskColor(band: string): string {
  switch (band.toLowerCase()) {
    case "low": return COLORS.riskLow;
    case "moderate": return COLORS.riskModerate;
    case "high": return COLORS.riskHigh;
    case "very high": return COLORS.riskVeryHigh;
    default: return COLORS.riskModerate;
  }
}

function getDimensionColor(level: string): string {
  switch (level.toLowerCase()) {
    case "low": return COLORS.riskLow;
    case "medium": return COLORS.riskModerate;
    case "high": return COLORS.riskHigh;
    default: return COLORS.riskModerate;
  }
}

function addLogoToPage(doc: PDFKit.PDFDocument): void {
  const logoExists = fs.existsSync(LOGO_PATH);
  if (logoExists) {
    const pageWidth = doc.page.width;
    const logoWidth = 100;
    const logoX = pageWidth - 50 - logoWidth;
    const logoY = 20;
    doc.image(LOGO_PATH, logoX, logoY, { width: logoWidth });
  }
}

export async function renderDecisionMemoPDF(
  decision: DecisionObject,
  narrative: NarrativeOutput["decisionMemo"]
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.on("pageAdded", () => {
      addLogoToPage(doc);
    });

    addLogoToPage(doc);

    doc.moveDown(3);

    doc.fontSize(24).fillColor(COLORS.primary).text("MarginMix – Decision Memo", { align: "center" });
    doc.moveDown(2);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Decision Context");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.decisionContext, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    const riskColor = getRiskColor(decision.riskBand);
    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Margin Risk Verdict");
    doc.moveDown(0.5);
    doc.rect(50, doc.y, 495, 40).fillAndStroke(riskColor, riskColor);
    doc.fontSize(14).fillColor(COLORS.white).font("Helvetica-Bold").text(
      decision.marginRiskVerdict,
      60,
      doc.y - 35,
      { align: "center", width: 475 }
    );
    doc.y += 15;
    doc.moveDown(1);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.marginRiskVerdict, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Primary Drivers of Risk");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    narrative.primaryDriversOfRisk.forEach((driver) => {
      doc.text(`• ${driver}`, { lineGap: 3 });
    });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Pricing & Governance Implications");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.pricingGovernanceImplications, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("What Would Need to Change");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    narrative.whatWouldNeedToChange.forEach((change, index) => {
      doc.text(`${index + 1}. ${change}`, { lineGap: 3 });
    });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Recommendation");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.recommendation, { lineGap: 4 });

    doc.moveDown(2);
    doc.fontSize(8).fillColor(COLORS.gray).text(
      `Generated by MarginMix | Decision ID: ${decision.id} | ${new Date().toLocaleDateString()}`,
      { align: "center" }
    );

    doc.end();
  });
}

export async function renderAssessmentOutputPDF(
  decision: DecisionObject,
  narrative: NarrativeOutput["assessmentOutput"],
  openSignal: string | null
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.on("pageAdded", () => {
      addLogoToPage(doc);
    });

    addLogoToPage(doc);

    doc.moveDown(3);

    doc.fontSize(22).fillColor(COLORS.primary).text("MarginMix – Margin Risk Assessment Output", { align: "center" });
    doc.moveDown(2);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Executive Snapshot");
    doc.moveDown(0.5);
    const riskColor = getRiskColor(decision.riskBand);
    doc.rect(50, doc.y, 495, 35).fillAndStroke(riskColor, riskColor);
    doc.fontSize(12).fillColor(COLORS.white).font("Helvetica-Bold").text(
      `${decision.riskBand.toUpperCase()} RISK – ${decision.marginRiskVerdict}`,
      60,
      doc.y - 30,
      { align: "center", width: 475 }
    );
    doc.y += 10;
    doc.moveDown(1);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.executiveSnapshot, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Risk Dimension Summary");
    doc.moveDown(0.5);

    const dimensions = [
      { name: "Workforce Intensity", ...narrative.riskDimensionSummary.workforceIntensity },
      { name: "Coordination Entropy", ...narrative.riskDimensionSummary.coordinationEntropy },
      { name: "Commercial Exposure", ...narrative.riskDimensionSummary.commercialExposure },
      { name: "Volatility Control", ...narrative.riskDimensionSummary.volatilityControl }
    ];

    dimensions.forEach((dim) => {
      const dimColor = getDimensionColor(dim.level);
      doc.fontSize(11).fillColor(COLORS.dark).font("Helvetica-Bold").text(`${dim.name}: `, { continued: true });
      doc.fillColor(dimColor).text(dim.level);
      doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text(dim.description, { lineGap: 2 });
      doc.moveDown(0.6);
    });
    doc.moveDown(1);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Effort Bands & Allocation");
    doc.moveDown(0.5);

    const effortBands = [
      { name: "Senior Leadership", ...narrative.effortBandsAllocation.senior },
      { name: "Mid-Level (Account / Program)", ...narrative.effortBandsAllocation.midLevel },
      { name: "Execution Layer", ...narrative.effortBandsAllocation.execution }
    ];

    effortBands.forEach((band) => {
      doc.fontSize(11).fillColor(COLORS.dark).font("Helvetica-Bold").text(`${band.name}: `, { continued: true });
      doc.fillColor(COLORS.secondary).text(band.percentage);
      doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text(band.rationale, { lineGap: 2 });
      doc.moveDown(0.6);
    });
    doc.moveDown(1);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Structural Risk Signals");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray);
    narrative.structuralRiskSignals.forEach((signal) => {
      doc.text(`• ${signal}`, { lineGap: 3 });
    });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(14).fillColor(COLORS.dark).font("Helvetica-Bold").text("Override Conditions");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.gray).text(narrative.overrideConditions, { lineGap: 4 });
    doc.moveDown(1.5);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.lightGray).stroke();
    doc.moveDown(1);

    doc.fontSize(12).fillColor(COLORS.secondary).font("Helvetica-Bold").text("What This Assessment Measures");
    doc.moveDown(0.3);
    doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text(
      "Structural margin risk before commitment. This analysis evaluates workforce intensity, coordination complexity, and commercial exposure to predict margin erosion risk.",
      { lineGap: 3 }
    );
    doc.moveDown(1);

    doc.fontSize(12).fillColor(COLORS.secondary).font("Helvetica-Bold").text("What This Assessment Does Not Measure");
    doc.moveDown(0.3);
    doc.font("Helvetica").fontSize(10).fillColor(COLORS.gray).text(
      "Delivery performance, timesheet accuracy, or post-engagement execution quality. This is a pre-commitment structural assessment only.",
      { lineGap: 3 }
    );

    doc.moveDown(2);
    doc.fontSize(8).fillColor(COLORS.gray).text(
      `Generated by MarginMix | Decision ID: ${decision.id} | ${new Date().toLocaleDateString()}`,
      { align: "center" }
    );

    doc.end();
  });
}

export function generatePDFFilename(
  type: "decision_memo" | "assessment_output",
  fullName: string,
  organisationName: string
): string {
  const sanitize = (str: string) => str.replace(/[^a-zA-Z0-9]/g, "_").substring(0, 30);
  const name = sanitize(fullName);
  const org = sanitize(organisationName);
  const timestamp = Date.now();
  
  if (type === "decision_memo") {
    return `MMIX_Decision_Memo_${name}_${org}_${timestamp}.pdf`;
  }
  return `MMIX_Assessment_Output_${name}_${org}_${timestamp}.pdf`;
}
