import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  Download, 
  Target, 
  Users, 
  DollarSign, 
  Calendar, 
  MapPin,
  Briefcase,
  User,
  TrendingUp,
  ArrowRight
} from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface CampaignSummaryProps {
  sessionData: Record<string, any>;
  onContinue: () => void;
}

export function CampaignSummary({ sessionData, onContinue }: CampaignSummaryProps) {
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  const formatPlatforms = (platforms: string[] | string) => {
    if (Array.isArray(platforms)) {
      return platforms.join(", ");
    }
    return platforms || "Not specified";
  };

  const generatePDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const element = document.getElementById('campaign-summary-content');
      if (!element) return;

      const canvas = await html2canvas(element, {
        scale: 2,
        logging: false,
        useCORS: true,
        allowTaint: true
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const imgWidth = 210;
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      // Add company name to filename if available
      const companyName = sessionData.company || 'Campaign';
      const fileName = `${companyName.replace(/[^a-z0-9]/gi, '_')}_Campaign_Brief.pdf`;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(fileName);
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          Your Campaign Brief is Ready!
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-300">
          Here's a summary of your digital media campaign plan
        </p>
      </div>

      <div id="campaign-summary-content" className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8 mb-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h2 className="text-2xl font-bold text-blue-600 dark:text-blue-400 mb-2">
            Digital Media Campaign Brief
          </h2>
          <p className="text-gray-600 dark:text-gray-300">
            Generated by YourBrief AI Media Strategist
          </p>
          <div className="text-sm text-gray-500 mt-2">
            {new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Campaign Overview */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Target className="h-5 w-5 text-blue-600" />
                Campaign Overview
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {sessionData.name && (
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <User className="h-4 w-4 text-gray-500" />
                    <span className="font-medium">Contact:</span>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300">{sessionData.name}</p>
                </div>
              )}
              
              {sessionData.company && (
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <Briefcase className="h-4 w-4 text-gray-500" />
                    <span className="font-medium">Company:</span>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300">{sessionData.company}</p>
                </div>
              )}

              {sessionData.objective && (
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <TrendingUp className="h-4 w-4 text-gray-500" />
                    <span className="font-medium">Objective:</span>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300">{sessionData.objective}</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Product/Service */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Briefcase className="h-5 w-5 text-green-600" />
                Product/Service
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 dark:text-gray-300">
                {sessionData.product || "Not specified"}
              </p>
            </CardContent>
          </Card>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Target Audience */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="h-5 w-5 text-purple-600" />
                Target Audience
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 dark:text-gray-300">
                {sessionData.audience || "Not specified"}
              </p>
            </CardContent>
          </Card>

          {/* Campaign Details */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Calendar className="h-5 w-5 text-orange-600" />
                Campaign Details
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {sessionData.budget && (
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <DollarSign className="h-4 w-4 text-gray-500" />
                    <span className="font-medium">Budget:</span>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300">{sessionData.budget}</p>
                </div>
              )}
              
              {sessionData.duration && (
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <Calendar className="h-4 w-4 text-gray-500" />
                    <span className="font-medium">Duration:</span>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300">{sessionData.duration}</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Platforms */}
        {sessionData.platforms && (
          <Card className="mb-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Target className="h-5 w-5 text-blue-600" />
                Selected Platforms
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {formatPlatforms(sessionData.platforms).split(", ").map((platform, index) => (
                  <Badge key={index} variant="secondary" className="px-3 py-1">
                    {platform}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        <Separator className="my-8" />

        {/* Next Steps */}
        <div className="text-center">
          <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
            Next Steps
          </h3>
          <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-6">
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              Your campaign brief has been created! To access advanced features including:
            </p>
            <ul className="text-left text-gray-700 dark:text-gray-300 space-y-2 mb-4 max-w-md mx-auto">
              <li>• Live reach and frequency forecasting</li>
              <li>• Budget optimization recommendations</li>
              <li>• Platform-specific setup guides</li>
              <li>• Real-time campaign tracking</li>
            </ul>
            <p className="text-gray-700 dark:text-gray-300">
              Sign in to continue with the full YourBrief platform.
            </p>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center">
        <Button 
          onClick={generatePDF}
          disabled={isGeneratingPDF}
          variant="outline"
          size="lg"
          className="flex items-center gap-2"
        >
          <Download className="h-5 w-5" />
          {isGeneratingPDF ? "Generating Brief..." : "Download Brief"}
        </Button>
        
        <Button 
          onClick={onContinue}
          size="lg"
          className="flex items-center gap-2"
        >
          Continue to Full Platform
          <ArrowRight className="h-5 w-5" />
        </Button>
      </div>
    </div>
  );
}